### PR TITLE
Update packages + Travis CI

### PR DESCRIPTION
**Pull request by striezel**
Same idea as in twolfson/grunt-spritesmith#174 etc.

### CODE REVIEW

**Comment by twolfson** [comment]
Got side-tracked so no time to look at these tonight. Should land them by the end of the weekend, worst case end of next week

**Comment by striezel** [comment]
Alright. No need to rush.

**Comment by twolfson** [comment]
LGTM

**Comment by twolfson** [comment]
This has been released in `2.0.4`. Thanks for all these PRs =D

**Pull request merged**
